import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const font = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Todo list app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${font.className} bg-gray-100`}>{children}</body>
    </html>
  );
}
